FROM ros:jazzy-ros-base-noble

RUN apt-get update \
    && apt-get install -y --no-install-recommends ros-jazzy-ros-gz-sim python3-pip python3-venv \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /opt/ump
COPY . .
RUN python3 -m venv --system-site-packages /opt/ump-venv \
    && /opt/ump-venv/bin/python -m pip install --no-cache-dir .

ENV PATH="/opt/ump-venv/bin:${PATH}"

ENTRYPOINT ["/ros_entrypoint.sh"]
